AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - TheatriaShopDB

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  TheatriaShopDB:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub theatriashopdb-${Environment}-api
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: target/function.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          SHOPDB_API_USERNAME: !Sub "{{resolve:ssm:theatriashopdb-api-username-${Environment}}}"
          QUARKUS_DATASOURCE_USERNAME: !Sub "{{resolve:ssm:theatriashopdb-postgresql-username-${Environment}}}"
          QUARKUS_DATASOURCE_PASSWORD: !Sub "{{resolve:ssm:theatriashopdb-postgresql-password-${Environment}}}"
          QUARKUS_DATASOURCE_JDBC_URL: !Sub "{{resolve:ssm:theatriashopdb-postgresql-jdbc-url-${Environment}}}"
          QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT: 1800
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  TheatriaShopDBAPI:
    Description: TheatriaShopDB API URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: !Sub "TheatriaShopDBAPI-${Environment}"
