name: CICD
on:
  workflow_dispatch:
  push:
    branches: [ dev, master ]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build a cloud native executable
        run: mvn package -Pnative -Dquarkus.native.container-build=true

      - name: Deploy - Development
        if: endsWith(github.ref, '/dev')
        run: sam deploy -t sam.native.yaml --config-env dev

      - name: Deploy - Production
        if: endsWith(github.ref, '/master')
        run: sam deploy -t sam.native.yaml --config-env prod
